### ISSUE TITLE
No Issue! It WORKS!!!

### ISSUE THREAD

**Issue by freddiemixell** [kesuskim/v8js-prebuilt-ubuntu18.04#1]
Thank you so much this saves so much time compiling and I can confirm its working with PHP 7.2.24.

It does not work with PHP 7.3 so anyone out there trying to install v8js on PHP 7.3 save yourself some time and don't do it.

Thanks again @kesuskim!

**Comment by kesuskim** [comment]
Does not work with 7.3 ? :sweat_smile: Anyway I'm glad you get some use with this, really :smile:

**Comment by freddiemixell** [comment]
I tried originally to build V8 and V8js on my server but I was getting the same error as I did with this binary. Then I tried 7.2 because I saw you noted your php version was 7.2 and it worked right away.

**Comment by kesuskim** [comment]
Thanks for your information :smile: will be helpful for other developers.
